[package]
name = "zephyr-alloc"
version = "0.1.0"
authors = ["Steven Walter <swalter@lexmark.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zephyr-sys = { path = "../zephyr-sys" }
